### ISSUE TITLE
Поиграться со спринтом и гитом

### ISSUE THREAD

**Issue by vladpereskokov** [ilyamoskalev/Rest#1]
- [x] добавить .gitignore с .DS_Store, .idea/. А также удалить отовсюду .DS_Store
- [x] добавить /greeting с методом get. Параметр гет запроса: name: string. На выходе ты должен отдать ответ 200 и строку "Hello, <name>", где <name> - то, что передал клиент в орле через гетерогамии запрос
- [x] добавить /greeting с методом post. Параметр пост запроса: name: string. Передается в виде json объекта в теле запроса ({"name": "Ilya"}). Ты должен отдать 200 и вернуть json объект {"response": "Hello, <name>"}, где <name> - то, что передали в теле запроса

**Comment by ilyamoskalev** [comment]
done

**Comment by vladpereskokov** [comment]
Молорик
